name: Release

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Get project meta
        id: meta
        run: |
          RAW_NAME=$(jq -r '.pack.name // ""' pack.mcmeta)
          TRIMMED_NAME=$(echo "$RAW_NAME" | xargs)

          if [ -z "$TRIMMED_NAME" ]; then
            NAME="release"
          else
            NAME="$TRIMMED_NAME"
          fi
          
          echo "name=$NAME" >> "$GITHUB_OUTPUT"

      - name: Zip all files
        run: |
          zip -r ${{ steps.meta.outputs.name }}.zip . -x ".*"

      - name: Create a release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create ${{ github.ref_name }} --title "${{ github.ref_name }}" ${{ steps.meta.outputs.name }}.zip
